import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto ('https://icsstg-purplecobras.oraclecloud.rfsmart.com/webclient');
    
     //login for Superior Healthcare. Comment out purplecobras URL above.
     //await page.goto('https://icsstg-superiorhealthcare.oraclecloud.rfsmart.com/webclient');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('dev.one');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('RFSics1650');
  await page.getByRole('button', {name: 'Login'}).click();
  await page.getByRole('link', { name: 'QA Sandbox' }).click();
    //Superior Healthcare Webclient Menu - comment out QA Sandbox above
    //await page.getByRole('link', { name: 'MB Testing' }).click();
  await page.getByRole('link', { name: 'Create Delivery' }).click();
  await page.getByPlaceholder('Organization Code').click();
  await page.getByPlaceholder('Organization Code').fill('001');
  await page.getByPlaceholder('Organization Code').press('Enter');
  await page.getByRole('link', { name: 'Skip Photo' }).click();
  await page.getByPlaceholder('Delivery Recipient').click();
  await page.getByPlaceholder('Delivery Recipient').fill('AUTO');
  await page.getByPlaceholder('Delivery Recipient').press('Enter');
  await page.getByPlaceholder('Deliver To Location').click();
  await page.getByPlaceholder('Deliver To Location').fill('JAXAUTO');
  await page.getByPlaceholder('Deliver To Location').press('Enter');
  await page.getByPlaceholder('Notes').click();
  await page.getByPlaceholder('Notes').fill('AUTONOTES');
  await page.getByPlaceholder('Notes').press('Enter');
  await page.getByPlaceholder('Number of Pieces').click();
  await page.getByPlaceholder('Number of Pieces').fill('1');
  await page.getByPlaceholder('Number of Pieces').press('Enter');
  await page.getByRole('link', { name: 'List' }).click();
  await page.getByRole('cell', { name: '\\\\PRINT-SERV\\Lexmark-room' }).click();
  //Add multiple deliveries (uncomment lines below)
//   await page.getByRole('link', { name: 'Skip Photo' }).click();
//   await page.getByPlaceholder('Delivery Recipient').click();
//   await page.getByPlaceholder('Delivery Recipient').fill('AUTO');
//   await page.getByPlaceholder('Delivery Recipient').press('Enter');
//   await page.getByPlaceholder('Deliver To Location').click();
//   await page.getByPlaceholder('Deliver To Location').fill('JAXAUTO');
//   await page.getByPlaceholder('Deliver To Location').press('Enter');
//   await page.getByPlaceholder('Notes').click();
//   await page.getByPlaceholder('Notes').fill('AUTONOTES');
//   await page.getByPlaceholder('Notes').press('Enter');
//   await page.getByPlaceholder('Number of Pieces').click();
//   await page.getByPlaceholder('Number of Pieces').fill('1');
//   await page.getByPlaceholder('Number of Pieces').press('Enter');
//   await page.getByRole('link', { name: 'List' }).click();
//   await page.getByRole('cell', { name: '\\\\PRINT-SERV\\Lexmark-room' }).click();
//   await page.getByRole('link', { name: 'Skip Photo' }).click();
//   await page.getByPlaceholder('Delivery Recipient').click();
//   await page.getByPlaceholder('Delivery Recipient').fill('AUTO');
//   await page.getByPlaceholder('Delivery Recipient').press('Enter');
//   await page.getByPlaceholder('Deliver To Location').click();
//   await page.getByPlaceholder('Deliver To Location').fill('JAXAUTO');
//   await page.getByPlaceholder('Deliver To Location').press('Enter');
//   await page.getByPlaceholder('Notes').click();
//   await page.getByPlaceholder('Notes').fill('AUTONOTES');
//   await page.getByPlaceholder('Notes').press('Enter');
//   await page.getByPlaceholder('Number of Pieces').click();
//   await page.getByPlaceholder('Number of Pieces').fill('1');
//   await page.getByPlaceholder('Number of Pieces').press('Enter');
//   await page.getByRole('link', { name: 'List' }).click();
//   await page.getByRole('cell', { name: '\\\\PRINT-SERV\\Lexmark-room' }).click();
//   await page.getByRole('link', { name: 'Skip Photo' }).click();
//   await page.getByPlaceholder('Delivery Recipient').click();
//   await page.getByPlaceholder('Delivery Recipient').fill('AUTO');
//   await page.getByPlaceholder('Delivery Recipient').press('Enter');
//   await page.getByPlaceholder('Deliver To Location').click();
//   await page.getByPlaceholder('Deliver To Location').fill('JAXAUTO');
//   await page.getByPlaceholder('Deliver To Location').press('Enter');
//   await page.getByPlaceholder('Notes').click();
//   await page.getByPlaceholder('Notes').fill('AUTONOTES');
//   await page.getByPlaceholder('Notes').press('Enter');
//   await page.getByPlaceholder('Number of Pieces').click();
//   await page.getByPlaceholder('Number of Pieces').fill('1');
//   await page.getByPlaceholder('Number of Pieces').press('Enter');
//   await page.getByRole('link', { name: 'List' }).click();
//   await page.getByRole('cell', { name: '\\\\PRINT-SERV\\Lexmark-room' }).click();
//   await page.getByRole('link', { name: 'Skip Photo' }).click();
//   await page.getByPlaceholder('Delivery Recipient').click();
//   await page.getByPlaceholder('Delivery Recipient').fill('AUTO');
//   await page.getByPlaceholder('Delivery Recipient').press('Enter');
//   await page.getByPlaceholder('Deliver To Location').click();
//   await page.getByPlaceholder('Deliver To Location').fill('JAXAUTO');
//   await page.getByPlaceholder('Deliver To Location').press('Enter');
//   await page.getByPlaceholder('Notes').click();
//   await page.getByPlaceholder('Notes').fill('AUTONOTES');
//   await page.getByPlaceholder('Notes').press('Enter');
//   await page.getByPlaceholder('Number of Pieces').click();
//   await page.getByPlaceholder('Number of Pieces').fill('1');
//   await page.getByPlaceholder('Number of Pieces').press('Enter');
//   await page.getByRole('link', { name: 'List' }).click();
//   await page.getByRole('cell', { name: '\\\\PRINT-SERV\\Lexmark-room' }).click();
await page.getByRole('link', { name: 'Exit' }).click();
await page.getByRole('link', { name: 'Exit' }).click();
});